spring:
  profiles:
    default: local


  datasource:
    url: jdbc:h2:mem:~/familing;MODE=MYSQL;     #Mysql 방언 사용으로 h2 모드 변경
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true  # H2 콘솔 활성화
      path: /h2-console  # H2 콘솔 경로 설정

  jwt:
    secret: "vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb"

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: "kakao"
            client-id: "457176480b65c5c9ffe60bcd2202d3a3"
            #            client-secret: "457176480b65c5c9ffe60bcd2202d3a3"
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: "authorization_code"
        #            scope:
        #              - "name"
        provider:
          kakao:
            authorization-uri: "https://kauth.kakao.com/oauth/authorize"
            token-uri: "https://kauth.kakao.com/oauth/token"
            user-info-uri: "https://kapi.kakao.com/v2/user/me"
            user-name-attribute: "id"
mongodb:
  client: mongodb://root:1234@127.0.0.1:27017/familing
  name: familing

kafka:
  server: localhost:9092
---

spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # MySql 방언으로 변경
        format_sql: true
    defer-datasource-initialization: true # (2.5~) Hibernate 초기화 이후 data.sql을 실행시켜 줌 (false로 할 경우 Hibernate 초기화 이전에 실행되어 오류 발생)

  h2:
    console:
      enabled: true


---

spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never # init sql 실행 안 함, 직접 데이터 초기화

#server:
#  port: 8000
#  ssl:
#    enabled: true //이후 프론트가 https 서버 사용시 필요)


mongodb:
  client: mongodb://root:1234@127.0.0.1:27017/testdb
  name: testdb

kafka:
  bootstrap-servers: localhost:9092

